#if DEBUG 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;

namespace iSql.Validator.Test {
    [TestFixture]
    class TestSpExcuteSql : TestValidateSqlBase {

        public override void InitSqlTestingScripts() {

            BadSqlScripts.AddRange(_BadSqlScripts);
            GoodSqlScripts.AddRange(_GoodSqlScripts);

            enTargets = (from val in SqlValidation.sqlValidators
                         where val.title == "SpExecuteSql"
                         select val);
        }

        private string[] _BadSqlScripts = new string[] {

            @"sp_executesql N'select @@LOCK_TIMEOUT ' " , 

            // ------------------------------------------------------------------------
            // Real world _UGLY_ sql generated by nasty EF framework
            // ------------------------------------------------------------------------
            @"
            exec sp_executesql N'SELECT 
            [Project2].[TicketId] AS [TicketId], 
            [Project2].[Description] AS [Description], 
            [Project2].[ProjectId] AS [ProjectId], 
            [Project2].[UserId] AS [UserId], 
            [Project2].[CreatedAt] AS [CreatedAt]
            FROM ( SELECT 
               [Extent1].[TicketId] AS [TicketId], 
               [Extent1].[Description] AS [Description], 
               [Extent1].[ProjectId] AS [ProjectId], 
               [Extent1].[UserId] AS [UserId], 
               [Extent1].[CreatedAt] AS [CreatedAt]
               FROM [dbo].[Tickets] AS [Extent1]
               WHERE ([Extent1].[UserId] <> @p__linq__0) AND ( EXISTS (SELECT 
                   1 AS [C1]
                   FROM [dbo].[Accesses] AS [Extent2]
                   WHERE ([Extent2].[UserId] = @p__linq__1) AND ([Extent2].[ProjectId] = [Extent1].[ProjectId])
               ))
            )  AS [Project2]
            ORDER BY [Project2].[CreatedAt] DESC',N'@p__linq__0 nvarchar(4000),@p__linq__1 nvarchar(4000)',@p__linq__0=N'josh.davison',@p__linq__1=N'josh.davison'
            "
       };


        private string[] _GoodSqlScripts = new string[] {
                                                   
            @"SELECT * FROM SomeTable ", 
        };


    }
}

#endif