/*
  This script is used to modifiy the FK constrains generated by Entity Framework 4.x.
  
  Unforutuantely, for code first approach, there's no easy way to ask EF to go for UPDATE  CASCADE option, so we end up writing our modificdation script here.

*/


-- alter Access_User FK constrain

ALTER TABLE dbo.Accesses
	DROP CONSTRAINT Access_User
go


ALTER TABLE dbo.Accesses ADD CONSTRAINT
	Access_User FOREIGN KEY
	(
	User_UserId
	) REFERENCES dbo.Users
	(
	UserId
	) ON UPDATE  CASCADE 
	 ON DELETE  NO ACTION 
go


-- for now, we don't need to modify [Project_Accesses] FK constrain

-- alter [Ticket_CreatedBy] FK constrain

ALTER TABLE dbo.Tickets
	DROP CONSTRAINT Ticket_CreatedBy

go

ALTER TABLE dbo.Tickets ADD CONSTRAINT
	Ticket_CreatedBy FOREIGN KEY
	(
	UserId
	) REFERENCES dbo.Users
	(
	UserId
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	

-- the Authorized_By from 

ALTER TABLE [dbo].[WorkStates]  WITH CHECK ADD  CONSTRAINT 
	[WorkStates_AuthorizedBy] FOREIGN KEY
	(
	AuthorizedBy
	) REFERENCES dbo.Users
	(
	UserId
	) ON UPDATE  CASCADE 
	 ON DELETE  NO ACTION 
